[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.4.0"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/Workiva/go-datastructures"
  version = "1.0.50"

[[constraint]]
  name = "github.com/go-kit/kit"
  version = "0.8.0"

[[constraint]]
  name = "github.com/jinzhu/configor"
  version = "1.0.0"

[[constraint]]
  name = "github.com/marcusolsson/tui-go"
  version = "0.4.0"

[[constraint]]
  name = "github.com/julienschmidt/httprouter"
  version = "1.2.0"
  
